### ISSUE TITLE
About cluster error

### ISSUE THREAD

**Issue by pysjp** [anyflow/lannister#37] opened 2016-08-12 08:16 UTC
When i test cluster on different virtual machine,i got following error message:
严重: [114.215.239.152]:5702 [dev] [3.6.2] Failed to process packet:Packet{header=32, isResponse=false, isOperation=false, isEvent=false, partitionId=-1, conn=Connection [/10.165.39.99:5702 -> /10.161.158.133:60500], endpoint=null, alive=true, type=MEMBER}
com.hazelcast.nio.serialization.HazelcastSerializationException: There is no suitable de-serializer for type 65536. This exception is likely to be caused by differences in the serialization configuration between members or between clients and members.
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.newHazelcastSerializationException(AbstractSerializationService.java:183)
	at com.hazelcast.internal.serialization.impl.AbstractSerializationService.toObject(AbstractSerializationService.java:165)
	at com.hazelcast.nio.tcp.TcpIpConnectionManager.handle(TcpIpConnectionManager.java:233)
	at com.hazelcast.spi.impl.NodeEngineImpl$ConnectionManagerPacketHandler.handle(NodeEngineImpl.java:124)
	at com.hazelcast.spi.impl.packetdispatcher.impl.PacketDispatcherImpl.dispatch(PacketDispatcherImpl.java:63)
	at com.hazelcast.nio.tcp.MemberReadHandler.handlePacket(MemberReadHandler.java:75)
	at com.hazelcast.nio.tcp.MemberReadHandler.onRead(MemberReadHandler.java:58)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingSocketReader.handle(NonBlockingSocketReader.java:178)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKey(NonBlockingIOThread.java:271)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.handleSelectionKeys(NonBlockingIOThread.java:256)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.runSelectLoop(NonBlockingIOThread.java:206)
	at com.hazelcast.nio.tcp.nonblocking.NonBlockingIOThread.run(NonBlockingIOThread.java:163)

BTW I used the default config

**Comment by anyflow** [comment] 2016-09-11 09:34
Thanks for your contribution & sorry for late response.

Unfortunately, I could not reproduce your failure. Needed more detailed reproduce description.

I close the issue, you may reopen it with further information about it.

BTW Version 0.9.5.2 released,
which includes some fixing and updating related to clustering features.
For details, Refer README.md which includes updated version history.

**Closed by anyflow** 2016-09-11 09:34 UTC
